### ISSUE TITLE
set `requires-python` as minimum bound rather than ~=

### ISSUE THREAD

**Issue by oliver-tosky-sh** [PrestonBlackburn/ice_pick#10]
Really like the work you've done here!

Would you be open to expanding the Python version constraints as a minimum bound instead of `~=`?  Are there any reasons why that constraint was set?

**Comment by PrestonBlackburn** [comment]
Hey, thanks! That constraint was originally because Snowpark used to only support Python 3.8. Now Snowpark supports Python 3.8-3.11, so there is no need for that constraint. 

I just updated the package (now version 0.0.6) to remove the 3.8 restriction, so hopefully that helps!

**Comment by oliver-tosky-sh** [comment]
Thanks!  Appreciate the speedy fix!
